version: '3.8'

services:
  dev-mikefritzsche-react-app:
    container_name: dev-mikefritzsche-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-mikefritzsche-react-app.rule=Host(`dev.mikefritzsche.localhost`)"
      - "traefik.http.services.dev-mikefritzsche-react-app.loadbalancer.server.port=5173"
    networks:
      - proxy

networks:
  proxy:
    external: true
