version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18-browsers

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t mfritzsche/my-react-app:${CIRCLE_SHA1} .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push mfritzsche/my-react-app:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
