version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Set up SSH key for DigitalOcean
          command: |
            mkdir -p ~/.ssh
            echo "$DO_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $DO_MIKE_SERVER_IP >> ~/.ssh/known_hosts
      - run:
          name: Build and Push Docker image
          command: |
            SHORT_SHA=$(echo "${CIRCLE_SHA1}" | cut -c1-8)
            docker build -t ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA}
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $DO_SSH_USER@$DO_MIKE_SERVER_IP "
              docker pull ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} &&
              docker stop mikefritzsche-dev || true &&
              docker rm mikefritzsche-dev || true &&
              docker run -d --name mikefritzsche-dev --network proxy -p 80:80 ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} &&
              echo 'Deployed image with SHA: ${SHORT_SHA}' >> /path/to/deployment-log.txt
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: do-secrets  # Apply context at the workflow level
