version: 2.1

orbs:
  slack: circleci/slack@4.6.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install jq and semver
          command: |
            sudo apt-get update && sudo apt-get install -y jq
            npm install semver
      - run:
          name: Determine Next Semantic Version
          command: |
            set -e
            git fetch --tags
            CURRENT_VERSION=$(git tag --list | sort -V | tail -n1)
            echo "CURRENT_VERSION=${CURRENT_VERSION}"
            if [ -z "$CURRENT_VERSION" ]; then
              NEW_VERSION="1.0.0"
            else
              NEW_VERSION=$(npx semver -i patch "${CURRENT_VERSION}")
            fi
            
            while git rev-parse "${NEW_VERSION}" >/dev/null 2>&1; do
              echo "Tag ${NEW_VERSION} already exists. Incrementing patch version."
              NEW_VERSION=$(npx semver -i patch "${NEW_VERSION}")
            done
            
            echo "NEW_VERSION=${NEW_VERSION}" >> build.env
            echo "New version determined: ${NEW_VERSION}"
      - run:
          name: Build and Save Docker image
          command: |
            source build.env
            IMAGE_NAME="mikefritzsche-dev:${NEW_VERSION}"
            docker build -t ${IMAGE_NAME} .
            docker save ${IMAGE_NAME} | gzip > image.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - build.env
            - image.tar.gz

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Configure Git
          command: |
            git config --global user.email "ci@example.com"
            git config --global user.name "CircleCI"
      - run:
          name: Deploy to DigitalOcean
          command: |
            source build.env
            TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
            
            # Copy the Docker image to the server
            scp -o StrictHostKeyChecking=no image.tar.gz $DO_SSH_USER@$DO_MIKE_SERVER_IP:/tmp/
            
            # Load and run the image on the server
            ssh -o StrictHostKeyChecking=no $DO_SSH_USER@$DO_MIKE_SERVER_IP "
              # Load the Docker image
              docker load < /tmp/image.tar.gz &&
              rm /tmp/image.tar.gz &&
            
              # Stop and remove existing container
              docker stop mikefritzsche-dev-react-app || true &&
              docker rm mikefritzsche-dev-react-app || true &&
            
              # Run the new container
              docker run -d --name mikefritzsche-dev-react-app \
                --label traefik.enable=true \
                --label traefik.http.routers.prod-mikefritzsche-react-app.rule=Host\\(\\\`dev.mikefritzsche.com\\\`\\) \
                --label traefik.http.routers.prod-mikefritzsche-react-app.entrypoints=websecure \
                --label traefik.http.services.prod-mikefritzsche-react-app.loadbalancer.server.port=80 \
                --network proxy \
                mikefritzsche-dev:${NEW_VERSION} &&
            
              echo '[${TIMESTAMP}] Deployed version: ${NEW_VERSION}' >> /home/mikefritzsche/app/main-dev/deployment-log.txt
            "
      - run:
          name: Create Git Tag and Push
          command: |
            source build.env
            git tag "${NEW_VERSION}"
            git push https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git "${NEW_VERSION}"
      - slack/notify:
          event: pass
          template: basic_success
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment Success*: Version ${NEW_VERSION} has been deployed successfully."
                  }
                }
              ]
            }
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
            - do-secrets
            - slack-secrets
      - deploy:
          context:
            - do-secrets
            - slack-secrets
          requires:
            - build
