version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and Push Docker image
          command: |
            # Truncate the Git commit hash to the first 7 characters
            SHORT_SHA=$(echo "${CIRCLE_SHA1}" | cut -c1-7)
            
            # Build the Docker image with the truncated commit hash as the tag
            docker build -t mikefritzsche-dev:${SHORT_SHA} .
            
            # Login to Docker Hub using credentials from the context
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            
            # Push the image to Docker Hub
            docker push mikefritzsche-dev:${SHORT_SHA}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: do-secrets  # Apply context at the workflow level
