version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nO6gr+FnuBT6+A/J49EjMDjuem5wM4zp0wbAYhFKOps"  # Replace with the actual fingerprint of the SSH key added in project settings
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and Push Docker image
          command: |
            SHORT_SHA=$(echo "${CIRCLE_SHA1}" | cut -c1-8)
            docker build -t ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA}
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh -o StrictHostKeyChecking=no $DO_SSH_USER@$DO_MIKE_SERVER_IP "
              docker pull ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} &&
              docker stop mikefritzsche-dev || true &&
              docker rm mikefritzsche-dev || true &&
              docker run -d --name mikefritzsche-dev --network proxy -p 80:80 ${DOCKER_USERNAME}/mikefritzsche-dev:${SHORT_SHA} &&
              echo 'Deployed image with SHA: ${SHORT_SHA}' >> /path/to/deployment-log.txt
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: do-secrets  # Apply context at the workflow level
